using System.Runtime.Serialization;

namespace ESI.Sharp.Models.Enumerations.Static
{
    /// <summary>
    /// Some of ESI methods require special scopes to be enabled for an access token. This is the list of all scopes used in the Endpoints
    /// </summary>
    public enum Scope
    {
        [EnumMember(Value = "esi-alliances.read_contacts.v1")] AlliancesReadContacts,
        [EnumMember(Value = "esi-assets.read_assets.v1")] AssetsReadAssets,
        [EnumMember(Value = "esi-assets.read_corporation_assets.v1")] AssetsReadCorporationAssets,
        [EnumMember(Value = "esi-bookmarks.read_character_bookmarks.v1")] BookmarksReadCharacterBookmarks,
        [EnumMember(Value = "esi-bookmarks.read_corporation_bookmarks.v1")] BookmarksReadCorporationBookmarks,
        [EnumMember(Value = "esi-calendar.read_calendar_events.v1")] CalendarReadCalendarEvents,
        [EnumMember(Value = "esi-calendar.respond_calendar_events.v1")] CalendarRespondCalendarEvents,
        [EnumMember(Value = "esi-characters.read_agents_research.v1")] CharactersReadAgentsResearch,
        [EnumMember(Value = "esi-characters.read_blueprints.v1")] CharactersReadBlueprints,
        [EnumMember(Value = "esi-characters.read_contacts.v1")] CharactersReadContacts,
        [EnumMember(Value = "esi-characters.read_corporation_roles.v1")] CharactersReadCorporationRoles,
        [EnumMember(Value = "esi-characters.read_fatigue.v1")] CharactersReadFatigue,
        [EnumMember(Value = "esi-characters.read_fw_stats.v1")] CharactersReadFWStats,
        [EnumMember(Value = "esi-characters.read_loyalty.v1")] CharactersReadLoyalty,
        [EnumMember(Value = "esi-characters.read_medals.v1")] CharactersReadMedals,
        [EnumMember(Value = "esi-characters.read_notifications.v1")] CharactersReadNotifications,
        [EnumMember(Value = "esi-characters.read_opportunities.v1")] CharactersReadOpportunities,
        [EnumMember(Value = "esi-characters.read_standings.v1")] CharactersReadStandings,
        [EnumMember(Value = "esi-characters.read_titles.v1")] CharactersReadTitles,
        [EnumMember(Value = "esi-characters.write_contacts.v1")] CharactersWriteContacts,
        [EnumMember(Value = "esi-clones.read_clones.v1")] ClonesReadClones,
        [EnumMember(Value = "esi-clones.read_implants.v1")] ClonesReadImplants,
        [EnumMember(Value = "esi-contracts.read_character_contracts.v1")] ContractsReadCharacterContracts,
        [EnumMember(Value = "esi-contracts.read_corporation_contracts.v1")] ContractsReadCorporationContracts,
        [EnumMember(Value = "esi-corporations.read_blueprints.v1")] CorporationsReadBlueprints,
        [EnumMember(Value = "esi-corporations.read_contacts.v1")] CorporationsReadContacts,
        [EnumMember(Value = "esi-corporations.read_container_logs.v1")] CorporationsReadContainerLogs,
        [EnumMember(Value = "esi-corporations.read_corporation_membership.v1")] CorporationsReadCorporationMembership,
        [EnumMember(Value = "esi-corporations.read_divisions.v1")] CorporationsReadDivisions,
        [EnumMember(Value = "esi-corporations.read_facilities.v1")] CorporationsReadFacilities,
        [EnumMember(Value = "esi-corporations.read_fw_stats.v1")] CorporationsReadFWStats,
        [EnumMember(Value = "esi-corporations.read_medals.v1")] CorporationsReadMedals,
        [EnumMember(Value = "esi-corporations.read_standings.v1")] CorporationsReadStandings,
        [EnumMember(Value = "esi-corporations.read_starbases.v1")] CorporationsReadStarbases,
        [EnumMember(Value = "esi-corporations.read_structures.v1")] CorporationsReadStructures,
        [EnumMember(Value = "esi-corporations.read_titles.v1")] CorporationsReadTitles,
        [EnumMember(Value = "esi-corporations.track_members.v1")] CorporationsTrackMembers,
        [EnumMember(Value = "esi-fittings.read_fittings.v1")] FittingsReadFittings,
        [EnumMember(Value = "esi-fittings.write_fittings.v1")] FittingsWriteFittings,
        [EnumMember(Value = "esi-fleets.read_fleet.v1")] FleetsReadFleet,
        [EnumMember(Value = "esi-fleets.write_fleet.v1")] FleetsWriteFleet,
        [EnumMember(Value = "esi-industry.read_character_jobs.v1")] IndustryReadCharacterJobs,
        [EnumMember(Value = "esi-industry.read_character_mining.v1")] IndustryReadCharacterMining,
        [EnumMember(Value = "esi-industry.read_corporation_jobs.v1")] IndustryReadCorporationJobs,
        [EnumMember(Value = "esi-industry.read_corporation_mining.v1")] IndustryReadCorporationMining,
        [EnumMember(Value = "esi-killmails.read_corporation_killmails.v1")] KillmailsReadCorporationKillmails,
        [EnumMember(Value = "esi-killmails.read_killmails.v1")] KillmailsReadKillmails,
        [EnumMember(Value = "esi-location.read_location.v1")] LocationReadLocation,
        [EnumMember(Value = "esi-location.read_online.v1")] LocationReadOnline,
        [EnumMember(Value = "esi-location.read_ship_type.v1")] LocationReadShipType,
        [EnumMember(Value = "esi-mail.organize_mail.v1")] MailOrganizeMail,
        [EnumMember(Value = "esi-fittings.read_fittings.v1")] MailReadMail,
        [EnumMember(Value = "esi-mail.send_mail.v1")] MailSendMail,
        [EnumMember(Value = "esi-markets.read_character_orders.v1")] MarketsReadCharacterOrders,
        [EnumMember(Value = "esi-markets.read_corporation_orders.v1")] MarketsReadCorporationOrders,
        [EnumMember(Value = "esi-markets.structure_markets.v1")] MarketsStructureMarkets,
        [EnumMember(Value = "esi-planets.manage_planets.v1")] PlanetsManagePlanets,
        [EnumMember(Value = "esi-planets.read_customs_offices.v1")] PlanetsReadCustomsOffices,
        [EnumMember(Value = "esi-search.search_structures.v1")] SearchSearchStructures,
        [EnumMember(Value = "esi-skills.read_skillqueue.v1")] SkillsReadSkillqueue,
        [EnumMember(Value = "esi-skills.read_skills.v1")] SkillsReadSkills,
        [EnumMember(Value = "esi-ui.open_window.v1")] UIOpenWindow,
        [EnumMember(Value = "esi-ui.write_waypoint.v1")] UIWriteWaypoint,
        [EnumMember(Value = "esi-universe.read_structures.v1")] UniverseReadStructures,
        [EnumMember(Value = "esi-wallet.read_character_wallet.v1")] WalletReadCharacterWallet,
        [EnumMember(Value = "esi-wallet.read_corporation_wallets.v1")] WalletReadCorporationWallets,
    }
}