name: .NET NuGet push

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Get the tag name
        run: echo "VERSION_NUMBER=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Set Nuget Package Version
        uses: roryprimrose/set-vs-sdk-project-version@v1
        with:
          version: ${{ env.VERSION_NUMBER }}
          assemblyVersion: ${{ env.VERSION_NUMBER }}
          fileVersion: ${{ env.VERSION_NUMBER }}
          informationalVersion: ${{ env.VERSION_NUMBER }}

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Define Package Name
        run: echo 'PACKAGE_NAME=$"ESI.Sharp/bin/Release/ESI.Sharp.${{ env.VERSION_NUMBER }}.nupkg" ' >> $GITHUB_ENV

      - name: Generate a NuGet package
        run: dotnet pack --no-build --include-symbols -p:SymbolPackageFormat=snupkg -o .

      - name: Publish nupkg
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}

      - name: Publish snupkg
        run: nuget push **\*.snupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}